name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  LAMBDA_FUNCTION_NAME: Liam-Barkley-Lambda-Function-Python

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install awscli pytest

      # - name: Run unit tests
      #   run: |
      #     python -m unittest discover -s . -p 'test_*.py'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip the Lambda function
        run: zip function.zip lambda_function.py

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://./function.zip

      - name: Clean up
        run: rm function.zip